### ISSUE TITLE
backend.auth.externalAccess指定へ移行

### ISSUE THREAD

**Issue by apc-kamezaki** [ap-communications/chocott-backstage#218]
```
backstage warn DEPRECATION WARNING: The backend.auth.keys config has been replaced by backend.auth.externalAccess, see https://backstage.io/docs/auth/service-to-service-auth 
```

ということで、backend.auth.keysの指定の変更が必要か。

```yaml
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${CICD_TOKEN}
          subject: cicd-system-completion-events
      - type: static
        options:
          token: ${ADMIN_CURL_TOKEN}
          subject: admin-curl-access
```
